config/routes.rb
Rails.application.routes.draw do
  devise_for :user_logins

  root 'admin#index'

  get 'admin'                                   => 'admin#index'

  get 'admin/users/:role'                       => 'admin/users#index'
  get 'admin/users/:role/new'                   => 'admin/users#new'
  post 'admin/users/:role/new'                  => 'admin/users#create'
  get 'admin/users/:role/edit/:id'              => 'admin/users#edit'

  post 'admin/users/validate-email-uniqueness'  => 'admin/users#validate_email_uniqueness'

  get 'hos' => 'hos#index'

  get 'hos/products'                            => 'hos/products#index'
  get 'hos/products/new'                        => 'hos/products#new'
  post 'hos/products/new'                       => 'hos/products#create'
  get 'hos/products/edit/:id'                   => 'hos/products#edit'

  get 'hr' => 'hr#index'
  post 'hr/filter' => 'hr#filter'

end

app/models/admin_profile.rb
class AdminProfile < ActiveRecord::Base
  has_one :user_login, as: :loginable
end

app/models/hos_profile.rb
class HosProfile < ActiveRecord::Base
  has_one :user_login, as: :loginable
end

app/models/hr_profile.rb
class HrProfile < ActiveRecord::Base
  has_one :user_login, as: :loginable
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user_login.rb
class UserLogin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :loginable, polymorphic: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController


  layout "admin"

  before_filter :authenticate_user_login!

  def index
    check_role_param(params['role'])
    case params['role']
      when "head-of-sales"
        @users = HosProfile.all
        @title = "Head of Sales Users List"
      when "hr"
        @users = HrProfile.all
        @title = "HR Users List"
    end
  end

  def new
    check_role_param(params['role'])
    @user = HosProfile.new

    case params['role']
      when "head-of-sales"
        @role = "hos"
        @title = "New Head of Sales User"
      when "hr"
        @role = "hr"
        @title = "New HR user"
    end
  end

  def create
    check_role_param(params['role'])
    role = params[:user][:role]

    if role == "hos"
      @user = HosProfile.new(user_params)
      success_notice = "Successfully created Head of Sales user!"
    elsif role == "hr"
      @user = HrProfile.new(user_params)
      success_notice = "Successfully created HR user!"
    end

    if @user.save

      login = UserLogin.new
      login.email = user_params[:email]
      login.password = params[:password]
      login.role = role
      login.save

      login.loginable = @user
      login.save

      flash[:notice] = success_notice

      status = 1
    else

      status = 0
    end

    render json: { status: status, user: @user }
  end

  def edit
    check_role_param(params['role'])
    case params['role']
      when "head-of-sales"
        @user = HosProfile.find(params[:id])
        @role = "hos"
        @title = "Edit Head of Sales User"
      when "hr"
        @user = HrProfile.find(params[:id])
        @role = "hr"
        @title = "Edit HR user"
    end
  end

  def update
    @user = HosProfile.find(params[:id])
  end

  def validate_email_uniqueness
    errors = []
    user_login = UserLogin.where(["email = ?", params[:email]])
    if user_login.count > 0
      errors.push('Email already exist')
    end
    render json: { errors: errors }
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :date_of_birth, :email, :nric, :gender, :role)
  end

  def check_role_param(role)
    valid_role_param = ["head-of-sales", "hr"]
    if !valid_role_param.include?(role)
      redirect_to controller: "/admin", action: "index"
    end
  end


end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_filter :authenticate_user_login!

  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :validate_role

  def validate_role
    if user_login_signed_in?
      case current_user_login.role.downcase
        when "hos"
          allowed_controllers = ['devise/sessions', 'hos', 'hos/products']
          if !allowed_controllers.include?(params[:controller])
            redirect_to :controller => "/hos", :action => "index"
          end
        when "hr"
          allowed_controllers = ['devise/sessions', 'hr']
          if !allowed_controllers.include?(params[:controller])
            redirect_to :controller => "/hr", :action => "index"
          end
      end
    end
  end

  def after_sign_in_path_for(resource)
    case resource.role.downcase
      when resource.role == 'admin'
        admin_path
      when resource.role == 'hos'
        hos_path
      when resource.role == 'hr'
        hr_path
      else
        admin_path
    end
  end

end

app/controllers/hos/products_controller.rb
class Hos::ProductsController < ApplicationController

  layout "hos"

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully created!"
      status = 1
    else
      status = 0
    end
    render json: { status: status, product: @product }
  end

  def edit
    @product = Product.find(params[:id])
  end

  private

  def product_params
    params.require(:product).permit(:name, :premium, :coverage_type, :trip_type, :insurer_name)
  end

end

app/controllers/hos_controller.rb
class HosController < ApplicationController

  layout "hos"

  before_filter :authenticate_user_login!

  def index
  end

end

app/controllers/hr_controller.rb
class HrController < ApplicationController

  layout "hr"

  before_filter :authenticate_user_login!

  def index

    @products = Product.select(:insurer_name).distinct

  end

  def filter
    @products = Product.where(["insurer_name = ? AND coverage_type = ? AND trip_type = ?", params[:insurer_name], params[:coverage_type], params[:trip_type]])
    render json: { products: @products }
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hos/products_helper.rb
module Hos::ProductsHelper
end

app/helpers/hos_helper.rb
module HosHelper
end

app/helpers/hr_helper.rb
module HrHelper
end

app/views/admin/index.html.erb
<ul>
  <li><a href="<%= url_for controller: "/admin/users", action: "new", role: "head-of-sales" %>">Create Head of Sales</a></li>
  <li><a href="<%= url_for controller: "/admin/users", action: "new", role: "hr" %>">Create HR</a></li>
</ul>

app/views/admin/users/_form.html.erb
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<ul id="form-errors" style="display: none;" class="error-list">
  <li>Error 1</li>
</ul>

<%= form_for :user, html: { id: 'user-form', class: 'create', 'redirect-url': url_for(action: 'index', role: params[:role]) }  do |f| %>
  <%= f.hidden_field :role, :value => @role  %>
  <table>
    <tr>
      <td>First name:</td>
      <td><%= f.text_field :first_name %></td>
    </tr>
    <tr>
      <td>Last name:</td>
      <td><%= f.text_field :last_name %></td>
    </tr>
    <tr>
      <td>Date of Birth:</td>
      <td><%= f.text_field :date_of_birth, :class => "datepicker" %></td>
    </tr>
    <tr>
      <td>Email Address:</td>
      <td><%= f.text_field :email %></td>
    </tr>
    <tr>
      <td>NRIC/FIN:</td>
      <td><%= f.text_field :nric %></td>
    </tr>
    <tr>
      <td>Gender:</td>
      <td>
        <%#= f.text_field :gender %>

        Male <%= f.radio_button :gender, "Male" %>
        Female <%= f.radio_button :gender, "Female" %>

      </td>
    </tr>

    <tr>
      <td>Password:</td>
      <td><%= password_field_tag :password %></td>
    </tr>
    <tr>
      <td>Password Confirmation:</td>
      <td><%= password_field_tag :password_confirmation %></td>
    </tr>

  </table>
  <%= f.submit %>

  <!-- <span id="loader" style="display: none;">
    <div style="width: 50px; display: inline-block; position: relative; top: 7px;">
      <div id="floatingCirclesG">
        <div class="f_circleG" id="frotateG_01"></div>
        <div class="f_circleG" id="frotateG_02"></div>
        <div class="f_circleG" id="frotateG_03"></div>
        <div class="f_circleG" id="frotateG_04"></div>
        <div class="f_circleG" id="frotateG_05"></div>
        <div class="f_circleG" id="frotateG_06"></div>
        <div class="f_circleG" id="frotateG_07"></div>
        <div class="f_circleG" id="frotateG_08"></div>
      </div>
    </div>
  </span> -->

<% end %>

app/views/admin/users/edit.html.erb
<h3><%= @title %></h3>

<%= render :partial => 'form', locals: { user: @user }  %>

app/views/admin/users/index.html.erb
<h3>Product List</h3>

<a href="<%= url_for action: 'new' %>">Create</a>

<% if flash[:notice] %>
  <div class="flash-notice">
    <%= flash[:notice] %>  
  </div>
<% end %>

<table class="list" cellspacing="0">
  <tr>
    <td>First Name</td>
    <td>Last Name</td>
    <td>Date of Birth</td>
    <td>Email Address</td>
    <td>NRIC/FIN</td>
    <td>Gender</td>
    <td>&nbsp;</td>
  </tr>
  <% if @users %>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.date_of_birth.strftime("%d/%m/%Y") if user.date_of_birth %></td>
        <td><%= user.email %></td>
        <td><%= user.nric %></td>
        <td><%= user.gender %></td>
        <td>
          <a href="<%= url_for action: "edit", id: user.id %>">Edit</a>
          &nbsp;|&nbsp;
          <a href="#">Delete</a>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/admin/users/new.html.erb
<h3><%= @title %></h3>

<%= render :partial => 'form', locals: { user: @user, role: @role }  %>

app/views/hos/index.html.erb
<ul>
  <li><a href="<%= url_for controller: "/hos/products", action: "index" %>">Product List</a></li>
  <li><a href="<%= url_for controller: "/hos/products", action: "new" %>">Create Product</a></li>
</ul>

app/views/hos/products/_form.html.erb
<ul id="form-errors" style="display: none;" class="error-list"></ul>
<%= form_for :product, html: { id: 'product-form', class: 'create', 'redirect-url': url_for(action: 'index') }  do |f| %>
  <%= f.hidden_field :role, :value => @role  %>
  <table>
    <tr>
      <td>Product name:</td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td>Premium:</td>
      <td><%= f.text_field :premium, id: "premium" %></td>
    </tr>
    <tr>
      <td>Coverage Type:</td>
      <td>
        <%= f.radio_button :coverage_type, "Individual" %> Individual
        <%= f.radio_button :coverage_type, "Family" %> Family
      </td>
    </tr>
    <tr>
      <td>Trip:</td>
      <td>
        <%= f.radio_button :trip_type, "Single" %> Single 
        <%= f.radio_button :trip_type, "Anual" %> Anual
      </td>
    </tr>
    <tr>
      <td>Insurer Name:</td>
      <td><%= f.text_field :insurer_name %></td>
    </tr>
  </table>
  <a href="<%= url_for action: "index" %>">Cancel</a>
  &nbsp;
  <%= f.submit %>
<% end %>

app/views/hos/products/edit.html.erb
<h3><%= @title %></h3>

<%= render :partial => 'form', locals: { user: @user }  %>

app/views/hos/products/index.html.erb
<h3><%= @title %></h3>

<a href="<%= url_for controller: "/hos/products", action: "new" %>">Create</a>

<% if flash[:notice] %>
  <div class="flash-notice">
    <%= flash[:notice] %>  
  </div>
<% end %>

<table class="list" cellspacing="0">
  <tr>
    <th>Product Name</th>
    <th>Premium</th>
    <th>Coverage Type</th>
    <th>Trip Type</th>
    <th>Insurer</th>
    <th>&nbsp;</th>
  </tr>
  <% if @products %>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td style="text-align: right;">
          <%= number_with_precision(product.premium, :precision => 2, :delimiter => ',') %>  
        </td>
        <td><%= product.coverage_type %></td>
        <td><%= product.trip_type %></td>
        <td><%= product.insurer_name %></td>
        <td>
          <a href="<%= url_for action: "edit", id: product.id %>">Edit</a>
          &nbsp;|&nbsp;
          <a href="#">Delete</a>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/hos/products/new.html.erb
<h3>New Product</h3>

<%= render :partial => 'form', locals: { product: @product }  %>

app/views/hr/index.html.erb
<h3>Quick Qoute Form</h3>
<ul id="form-errors" style="display: none;" class="error-list"></ul>
<form action="<%= url_for action: "filter" %>" id="filter-form">
  <table>
    <tr>
      <td>Insurer:</td>
      <td>
        <select name="insurer_name">
          <option value="">-</option>
          <% if @products %>
            <% @products.each do |product| %>
              <option value="<%= product.insurer_name %>"><%= product.insurer_name %></option>
            <% end %>
          <% end %>
        </select>
      </td>
    </tr>
    <tr>
      <td>Coverage Type:</td>
      <td>
        <select name="coverage_type">
          <option value="">-</option>
          <option value="Individual">Individual</option>
          <option value="Family">Family</option>
        </select>
      </td>
    </tr>
    <tr>
      <td>Trip Type:</td>
      <td>
        <select name="trip_type">
          <option value="">-</option>
          <option value="Single">Single</option>
          <option value="Anual">Anual</option>
        </select>
      </td>
    </tr>
  </table>
  <button typpe="submit">Submit</button>
</form>

<style type="text/css">
  #product-result div.item { border: 1px solid #ccc; margin: 10px 0; padding: 10px 10px; }
  #product-result .item .details .title { display: inline-block; min-width: 130px; font-weight: bold; }
</style>

<div id="product-result">

  <!-- <div class="item">
    <div class="details">
      <span class="title">Insurer Name:</span>
      <span class="content">Asian Life</span>
    </div>
    <div class="details">
      <span class="title">Product Name:</span>
      <span class="content">Asian Life</span>
    </div>
    <div class="details">
      <span class="title">Coverage Type:</span>
      <span class="content">Asian Life</span>
    </div>
    <div class="details">
      <span class="title">Trip Type:</span>
      <span class="content">Asian Life</span>
    </div>
    <div class="details">
      <span class="title">Premium:</span>
      <span class="content">Asian Life</span>
    </div>
  </div> -->

</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrPortal</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <a href="<%= url_for admin_path %>">Home</a>
    <% if user_login_signed_in? %>
      &nbsp;|&nbsp;
      <a href="<%= url_for controller: "/admin/users", action: "index", role: "head-of-sales" %>">Head of Sales</a>
      &nbsp;|&nbsp;
      <a href="<%= url_for controller: "/admin/users", action: "index", role: "hr" %>">HR</a>
      &nbsp;|&nbsp;
      <%= link_to "Logout", destroy_user_login_session_path, method: :delete  %>
      &nbsp;|&nbsp;
      Welcome <%= current_user_login.loginable.email %>!
    <% else %>
      &nbsp;|&nbsp;
      <a href="<%= url_for new_user_login_session_path %>">Login</a>
    <% end %>
    <hr />

    <%= yield %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrPortal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/hos.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BR Portal - Head of Sales</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

    <style>
      .flash-notice { color: green; border: 1px solid green; padding: 10px 10px; margin: 20px 0; }

      table.list { border-left: 1px solid #ccc; border-top: 1px solid #ccc; }
      table.list td { border-right: 1px solid #ccc; border-bottom: 1px solid #ccc; padding: 5px 10px; }
    </style>
  </head>
  <body>

    <a href="<%= url_for hos_path %>">Home</a>
    <% if user_login_signed_in? %>
      &nbsp;|&nbsp;
      <%= link_to "Logout", destroy_user_login_session_path, method: :delete  %>
      &nbsp;|&nbsp;
      Welcome <%= current_user_login.loginable.first_name %>!
    <% else %>
      &nbsp;|&nbsp;
      <a href="<%= url_for new_user_login_session_path %>">Login</a>
    <% end %>
    <hr />

    <%= yield %>

  </body>
</html>

app/views/layouts/hr.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BR Portal - HR</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <style>
      .flash-notice { color: green; border: 1px solid green; padding: 10px 10px; margin: 20px 0; }

      table.list { border-left: 1px solid #ccc; border-top: 1px solid #ccc; }
      table.list td { border-right: 1px solid #ccc; border-bottom: 1px solid #ccc; padding: 5px 10px; }
    </style>
  </head>
  <body>

    <a href="<%= url_for hos_path %>">Home</a>
    <% if user_login_signed_in? %>
      &nbsp;|&nbsp;
      <%= link_to "Logout", destroy_user_login_session_path, method: :delete  %>
      &nbsp;|&nbsp;
      Welcome <%= current_user_login.loginable.first_name %>!
    <% else %>
      &nbsp;|&nbsp;
      <a href="<%= url_for new_user_login_session_path %>">Login</a>
    <% end %>
    <hr />

    <%= yield %>

  </body>
</html>